### PR TITLE
Fix deprecation warnings with Python-Markdown 3.x

### PR DESCRIPTION
**Pull request by aleksan4eg**
https://python-markdown.github.io/change_log/release-3.0/#md_globals-keyword-deprecated-from-extension-api 
https://python-markdown.github.io/change_log/release-3.0/#homegrown-ordereddict-has-been-replaced-with-a-purpose-built-registry

The priority number was arbitrarily chosen.

### CODE REVIEW

**Comment by BKPepe** [comment]
Could you send this to @AliciaSchep's [repository](https://github.com/AliciaSchep/markdown-lightbox), please? :) I think, it is always a good idea to contribute it back, when we forked from it. I know that her repository has no updates for a while, but it is possible that others might be curious about it and they don't need to do the same changes as you do. It might save them time, if they see, there is open pull request.

**Comment by aleksan4eg** [comment]
> Could you send this to @AliciaSchep's [repository](https://github.com/AliciaSchep/markdown-lightbox), please? :)

If you tell me how I will send :D Because now I can only operate with this one or do you want me to open a new PR to the original repo?

**Review by miska — APPROVED** [review]
Fine by me

**Comment by miska** [comment]
Here is the link to create a pull request https://github.com/AliciaSchep/markdown-lightbox/compare/master...turris-cz:markdown-lightbox:fix-deprecation-warnings

**Pull request merged**
